### ISSUE TITLE
palindrome is not correct

### ISSUE THREAD

**Issue by thierryH91200** [raywenderlich/swift-algorithm-club#272]
ref  : https://en.wikipedia.org/wiki/Palindrome

A palindrome is a word, phrase, number, or other sequence of characters which reads the same backward or forward, such as madam or kayak. Sentence-length palindromes may be written when allowances are made for adjustments to capital letters, punctuation, and word dividers, such as "A man, a plan, a canal, Panama!", "Was it a car or a cat I saw?" or "No 'x' in Nixon".

for this phrase "A man, a plan, a canal, Panama! " the answer is false

**Comment by thierryH91200** [comment]
why it is closed @kelvinlauKL ??
 without giving any explanation !!!
I do not find it very correct

**Comment by kelvinlauKL** [comment]
Yo @thierryH91200 

I apologize for closing this prematurely. I took another look at the palindrome implementation and I see what you mean.

The wikipedia description of the palindrome only checks the alphanumeric component of a `String`, whilst the current implementation would compare the punctuations as well. 

Currently this is what happens when you using the `palindromeCheck` function:

```
palindromeCheck(text: "A man, a plan, a canal, Panama!") // evaluates false
palindromeCheck(text: "A man a plan a canal Panama") // evaluates true
```

The two checks should both evaluate `true` based on the wikipedia description for Palindromes.

I'm going to add this to a list of outstanding issues for visibility (#316). Thanks for bringing this issue up @thierryH91200 👍
