### ISSUE TITLE
Question about Deque

### ISSUE THREAD

**Issue by shenyun2304** [raywenderlich/swift-algorithm-club#320]
Hi~

In the last example of trimming array

```swift
	[ x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, 1, 2, 3 ]
	                                |                             |
	                                capacity                      head
```
At this time, capacity = 10, head = 20

But, because of the `capacity > 10` condition,  the `dequeue()` method won't trim the array,

So I change the `capacity > 10` to `capacity >= 10`, It trim successfully, but net next graph bugs me.

```
	[ x, x, x, x, x, 1, 2, 3 ]
	              |
	              head
	              capacity
```

After the `dequeue()` method, capacity = 5,  and head = 5

So.... should the head and capacity point at .... `1`? 

or I misunderstood something?

Thanks

**Comment by kelvinlauKL** [comment]
Definitely looks suspicious...

// cc @hollance

**Comment by hollance** [comment]
Maybe the example isn't optimal because of that `capacity > 10` check. That check is there so that we don't trim very small arrays (because that's not really worth it). So the example is correct if you pretend this `capacity > 10` check does not exist.

I think you are right that `head` and `capacity` need to point at `1` after the trimming. I must have counted wrong -- a typical off-by-one error. ;-)

**Comment by shenyun2304** [comment]
Thank for reply, helps a lot.

**Comment by kelvinlauKL** [comment]
Added this to the bugs watchlist. Thanks!
