### ISSUE TITLE
Significantly Modifying Existing Entry

### ISSUE THREAD

**Issue by superlopuh** [raywenderlich/swift-algorithm-club#493]
### Category

- [ ] Bug
- [ ] Feature Request
- [x] Question

### Brief Intro

Hi, I'd like to significantly modify/rewrite an entry for one of the data structures. There are a few points that I'd like to improve on, and I have a feeling that I'd end up rewriting the whole piece. I'm not sure about how to do that with the respect due to the original author. Is the convention here that once there is an implementation it's not up for rewrites, or should I go ahead with a pull request?

**Comment by kelvinlauKL** [comment]
Good question. We haven't really had a significant rewrite of an existing topic yet. 

There are definitely more than a couple that can benefit from drastic refactors. Which topic are you thinking of rewriting?

**Comment by superlopuh** [comment]
The BitSet one. While it explains the concept really well, there are a few details that I'm not super happy with. I feel that the whole thing could improve by the `BitSet` being a `RangeReplaceableCollection` with more familiar subscripting behaviour, as well as a reformulation of what a word is, since it's not 64 bit on all platforms.

I'd like to make it clear that this isn't a list of complaints, rather things I noticed when reading the article.

I'm now thinking that I should write an article anyway, just for me, and it'll be easier to discuss whether the change is worth it with both versions being available.

**Comment by hollance** [comment]
My 2 cents as the original author:

- I think it's great to make these collections more like Swift built-in collections, so making it a `RangeReplaceableCollection` sounds like a good idea. However, it may not make sense to do this right from the beginning (or maybe it does). In any case, I think it's useful to explain only one concept at a time, to avoid confusing the reader (not everyone will know what a `RangeReplaceableCollection` is).

- I'm not really sure what you mean by "a reformulation of what a word is, since it's not 64 bit on all platforms". In this particular case, the word *is* 64-bit on all platforms (since that's how I chose it to be).

Note that I'm not opposed to people completely rewriting my articles (to be honest, I can't really remember writing this particular one 😄 ). As long as the end result is a better article, I'm all for it. 👍

**Comment by superlopuh** [comment]
Awesome hearing that from you, I'll have a go at it, and see where it takes me.

**Comment by kelvinlauKL** [comment]
Sounds good. Open a new PR when you want a review.

**Comment by superlopuh** [comment]
Hi, I recently found this in the depths of my todo list and decided to finish the code. Just thought I'd post my implementation here, so you guys can tell me whether you think it's worth writing up.

The only advantage is that the BitSet types now conform to SetAlgebra. I'm not sure if that has that much educational value in terms of the raw algorithm in the end, so I'll leave the decision of whether it's worth writing up to you.

[Gist with implementation](https://gist.github.com/superlopuh/35f0da7367a9995c2c771ca0d005d605)
