### ISSUE TITLE
LinkedList: append node method creates an extra node instance

### ISSUE THREAD

**Issue by Dario-Gasquez** [raywenderlich/swift-algorithm-club#651]
### Brief Intro
In LinkedList's current implementation the append node method generates an additional node instance 'newNode' which may not be needed (if the received node argument is used instead).

### More Details
```
    public func append(_ node: Node) {
        // let newNode = LinkedListNode(value: node.value) -> is this instance needed, why not use the argument node instead?
        if let lastNode = last {
            node.previous = lastNode
            lastNode.next = node
        } else {
            head = node
        }
    }
```

**Comment by shibi1306** [comment]
There is one possibility that since the node is passed as a reference type, it could have the values of **next** pointing some other Node, instead of **nil**. So in the computed properties like **last** will end up parsing values that are not in the list. **You could set the next of parameter node as nil in the beginning**. They chose to copy the value of the node.

They have directly referenced it now. 
`public func append(_ node: Node) {`
`        let newNode = node`

But this exposes the problem that I have mentioned on the top.

`var list = LinkedList<String>()`
`var testNodeThatIsGoingToBeAppended = LinkedList<String>.LinkedListNode(value: "Hello")`
`var testNodeThatIsNotGoingToBeAppended = LinkedList<String>.LinkedListNode(value: "LOL")`
`testNodeThatIsGoingToBeAppended.next = testNodeThatIsNotGoingToBeAppended`
`list.append(testNodeThatIsGoingToBeAppended)`
`print(list)`

output:
`[Hello LOL]`

I am new to Github. What should I do first? give a pull request or post an issue?

**Comment by kelvinlauKL** [comment]
Good points @Dario-Gasquez @shibi1306. 

Here's my take on it: 

The current implementation is non-destructive to other objects that share the passed-in `Node`. If we reused the node without making a copy, we'll have to choose between the following two behaviours:

1. As @shibi1306 suggests, modify the `next` property of the passed-in node to `nil`, and append the node.

2. Append the node without modifications.

If we're going with option **1**, then we need to be aware this operation is potentially destructive to all references that rely on that node. If we're going with option **2**, we'll need to accept that `append` can possibly adds multiple nodes to the end of the list. 

It's unclear to me which decision is best.

**Comment by kelvinlauKL** [comment]
Closing inactive issues 👍
