### ISSUE TITLE
binary search question

### ISSUE THREAD

**Issue by makthrow** [raywenderlich/swift-algorithm-club#74]
func binarySearch<T: Comparable>(a: [T], key: T, range: Range<Int>) -> Int? {
  if range.startIndex >= range.endIndex {
    // If we get here, then the search key is not present in the array.
    return nil

Can you answer why startIndex is >= endIndex rather than =   ?
I can't think of a situation where startIndex will ever be bigger than endIndex.

**Comment by hollance** [comment]
Paranoia. ;-) It might have been because I originally wrote it the other way around,

```if range.startIndex < range.endIndex { 
  /* do the search */
} else {
  return nil
}
```

And then I flipped the logic and turned `<` into `>=`. You can see that's how the iterative version still does it.

But you're right, the startIndex will never be greater than the endIndex. If that were the case, Swift would already give an error message because you can't do something like `10 ..< 9`. That is not a valid range.

**Comment by kelvinlauKL** [comment]
Going to close this issue because the question has been answered!
