### ISSUE TITLE
Select Minimum Maximum questions

### ISSUE THREAD

**Issue by makthrow** [raywenderlich/swift-algorithm-club#75]
There are two implementations of min/max, both of which are O(n).
Is there any reason to choose the second algorithm (comparing in pairs) over the first?

And, for swift's minElement() and maxElement(),
```
let array = [ 8, 3, 9, 4, 6 ]
array.minElement()   // This will return 3
array.maxElement()   // This will return 9

```
Did they use the first algorithm (one-by-one comparison) or the second (pair comparison)?

**Comment by hollance** [comment]
**O(n)** is a rough estimate of how fast a particular algorithm is. But one **O(n)** algorithm can be easily 10x faster than another **O(n)** algorithm on the same set of data. The only true way to find out which is faster (or better in some other sense) is to do performance tests in your app on actual hardware.

As for Swift's `minElement()` and `maxElement()`, good question! According to the docs, it's O(n). Let's take a look at the actual Swift standard library source code.

In https://github.com/apple/swift/blob/master/stdlib/public/core/SequenceAlgorithms.swift.gyb there is:

```swift
  public func min( ) {
    var it = makeIterator()
    guard var result = it.next() else { return nil }
    for e in IteratorSequence(it) {
      if e < result { result = e }
    }
    return result
  }
```

(Note that minElement and maxElement are renamed to min and max in the upcoming Swift 3.)

So this is a very simple algorithm that just steps through the sequence and looks at the elements one-by-one.

**Comment by makthrow** [comment]
thanks for the help!

So , they went with the slower one? Why would they do that, when the second one is faster (and therefore I assume, superior) in every instance?

**Comment by hollance** [comment]
By the second one you mean the code that calculates both min and max at the same time? That one is slower than just looking for min or max.

Or do you mean the k-th largest selection algorithm? Whether that is actually faster in practice depends on a lot of factors, such as:

- the size of the array: in practice most arrays are small and therefore a simple algorithm will be faster than a more complex algorithm
- the CPU cache: if an array is large and you "jump" back and forth between positions in the array then you may force the cache to reload large chunks of data; doing a simple loop from beginning to end will be much faster because then such reloads happen much less often

The only way to find out what works best is to test it on the actual data you'll be using.

**Comment by makthrow** [comment]
Oh right, I didn't take that into account.. thanks for the help! 
BTW your Swift code looks great.. I'm learning a lot :)

**Comment by chris-pilcher** [comment]
Thanks for the question makthrow! Please feel free to raise new issues/ask questions 😄
